### ISSUE TITLE
메인페이지

### ISSUE THREAD

**Issue by zzdh8** [zzdh8/ViewGorithm#2]
## 설명
메인페이지 제작 과정

- [x] vue project 생성
- [x] 메인페이지 제작
- [x] 메인 서비스 모달 페이지 제작

**Comment by Gun-taek** [comment]
## 메인 페이지 디자인 구상
메인 페이지 코드 구현 및 관련 이미지 생성 완료 ( 나중에 참고 부탁)

- [ViewGorithm_Project_MainPage.zip](https://github.com/zzdh8/ViewGorithm/files/14627790/ViewGorithm_Project_MainPage.zip)

**Comment by zzdh8** [comment]
위의 이미지를 참고해서 독자적인 디자인 생성

이 디자인을 토대로 피드백을 수용하면서 진행할 예정

![Main](https://github.com/zzdh8/ViewGorithm/assets/59731570/5ac11ec3-0a25-46ea-ab84-6add96d466b1)

**Comment by zzdh8** [comment]
# 설명
Header 부분 완성.

Tailwind css 적용함.

**Comment by zzdh8** [comment]
구현 기능과 서버에서 가져올 일부 데이터(img)를 제외한 메인 페이지 생성완료

**Comment by zzdh8** [comment]
메인 서비스 모달 제작 완료

**Comment by Gun-taek** [comment]
메인 로고 

![뷰고리즘 메인화면 로고](https://github.com/zzdh8/ViewGorithm/assets/133934005/e42972c4-a120-49ac-9542-52173f2e71b6)
