### ISSUE TITLE
ERD 구상 및 SQL 파일 업로드 

### ISSUE THREAD

**Issue by Gun-taek** [zzdh8/ViewGorithm#4]
# 설명

ERD 클라우드를 활용하여 ERD 설계도 구상 사진, 

 MariaDB를 이용하여 SQL 파일 업로드 완료
## 참고자료
[Dto_Create_Drop_sql.txt](https://github.com/zzdh8/ViewGorithm/files/14627982/Dto_Create_Drop_sql.txt)
![ERD 사진](https://github.com/zzdh8/ViewGorithm/assets/133934005/1f270ea6-3b97-4f2b-a3dd-2d3ee796c2ee)

**Comment by zzdh8** [comment]
maria DB -> mysql 로 변경사항 적용
